/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#012d1d",
        "primary-container": "#1b4332",
        "on-primary": "#ffffff",
        "on-primary-container": "#86af99",
        "primary-fixed": "#c1ecd4",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#274e3d",
        "secondary": "#116c4a",
        "secondary-container": "#a1f4c8",
        "on-secondary-container": "#1b724f",
        "secondary-fixed": "#a1f4c8",
        "secondary-fixed-dim": "#86d7ad",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#401b1b",
        "tertiary-container": "#5a302f",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#f5b7b4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d29895",
        "on-tertiary-fixed": "#331111",
        "on-tertiary-fixed-variant": "#673a39",
        "surface": "#f9faf6",
        "surface-container": "#eeeeeb",
        "surface-container-low": "#f3f4f1",
        "surface-container-high": "#e8e8e5",
        "surface-container-highest": "#e2e3e0",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e3e0",
        "surface-dim": "#dadad7",
        "surface-bright": "#f9faf6",
        "surface-tint": "#3f6653",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#414844",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f0f1ee",
        "inverse-primary": "#a5d0b9",
        "background": "#f9faf6",
        "on-background": "#1a1c1a",
        "bg-warm": "#F8F9FA",
        "text-charcoal": "#212529",
        "text-muted": "#6C757D",
        "border-subtle": "#DEE2E6",
        "accent-harvest": "#FFB703",
        "success-natural": "#2D6A4F",
        "warning-amber": "#FB8500",
        "danger-muted": "#E63946",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#717973",
        "outline-variant": "#c1c8c2",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "260px",
        "sidebar-collapsed": "80px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "max-width": "1440px"
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "title-lg": ["Manrope", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
